In [22]:
import torch
import numpy as np

In [23]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [24]:
data_np = np.array(data)
x_np = torch.tensor(data_np)

In [25]:
torch.from_numpy(data_np) == x_np

tensor([[True, True],
        [True, True]])

In [26]:
torch.rand_like(x_data, dtype=torch.float16)
# Float8 types have a string of letters appended -- is this due to architectural differences / different Float representations?

tensor([[0.0709, 0.8901],
        [0.2389, 0.3884]], dtype=torch.float16)

In [27]:
shape = (2,3,)
tensor = torch.rand(shape)

In [28]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
tensor = tensor.to(device)
tensor.device

device(type='cpu')

In [29]:
print(f"Random tensor: \n {tensor}")

tensor[:,2] = 1
print(f"Random tensor now: \n {tensor}")

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"dim1-catted tensor: \n {t1}")

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(f"dim0-catted tensor: \n {t1}")

Random tensor: 
 tensor([[0.3232, 0.7237, 0.7956],
        [0.2036, 0.8087, 0.5579]])
Random tensor now: 
 tensor([[0.3232, 0.7237, 1.0000],
        [0.2036, 0.8087, 1.0000]])
dim1-catted tensor: 
 tensor([[0.3232, 0.7237, 1.0000, 0.3232, 0.7237, 1.0000, 0.3232, 0.7237, 1.0000],
        [0.2036, 0.8087, 1.0000, 0.2036, 0.8087, 1.0000, 0.2036, 0.8087, 1.0000]])
dim0-catted tensor: 
 tensor([[0.3232, 0.7237, 1.0000],
        [0.2036, 0.8087, 1.0000],
        [0.3232, 0.7237, 1.0000],
        [0.2036, 0.8087, 1.0000],
        [0.3232, 0.7237, 1.0000],
        [0.2036, 0.8087, 1.0000]])


In [30]:
print(f"Multiplication is element-wise, a priori,\n{tensor * tensor}")
print(f"Mail your Matrix multiplication today!:n{tensor @ tensor.T}")

Multiplication is element-wise, a priori,
tensor([[0.1045, 0.5238, 1.0000],
        [0.0415, 0.6540, 1.0000]])
Mail your Matrix multiplication today!:ntensor([[1.6282, 1.6511],
        [1.6511, 1.6955]])


In [31]:
print(f"There is some unsexy tension between in-place operations and derivatives; thus, torch hates this trick. \n {tensor.add_(5)}")

There is some unsexy tension between in-place operations and derivatives; thus, torch hates this trick. 
 tensor([[5.3232, 5.7237, 6.0000],
        [5.2036, 5.8087, 6.0000]])


In [32]:
n = np.ones(4)
t1 = torch.tensor(n)
t2 = torch.from_numpy(n)
n[0] = 0
np.add(n, 1, out=n)
print(f"Numpy and Tensor love (explicit) sharing!\n {t1} \n {t2}")

t2[0] = 10
print(f"Both ways: \n {t2} \n {n}")

Numpy and Tensor love (explicit) sharing!
 tensor([1., 1., 1., 1.], dtype=torch.float64) 
 tensor([1., 2., 2., 2.], dtype=torch.float64)
Both ways: 
 tensor([10.,  2.,  2.,  2.], dtype=torch.float64) 
 [10.  2.  2.  2.]


In [33]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/jens/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1081)>