In [1]:
import ssl

import certifi
import torch
import numpy as np

# Some systems' OpenSSL trust store is missing the CA that signs torch.hub's
# download mirrors, causing CERTIFICATE_VERIFY_FAILED. Use certifi's bundle
# instead, which is kept up to date independently of the OS.
ssl._create_default_https_context = lambda: ssl.create_default_context(
    cafile=certifi.where()
)

In [ ]:
data = [[1, 2],[3, 4]]
torch.tensor(data)

tensor([[1, 2],
        [3, 4]])

In [4]:
data_np = np.array(data)
x_np = torch.tensor(data_np)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
torch.from_numpy(data_np) == x_np

tensor([[True, True],
        [True, True]])

In [5]:
torch.rand_like(x_data, dtype=torch.float16)
# Float8 types have a string of letters appended -- is this due to architectural differences / different Float representations?

tensor([[0.7227, 0.2375],
        [0.4783, 0.1995]], dtype=torch.float16)

In [6]:
shape = (2,3,)
tensor = torch.rand(shape)

In [7]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
tensor = tensor.to(device)
tensor.device

device(type='cpu')

In [8]:
print(f"Random tensor: \n {tensor}")

tensor[:,2] = 1
print(f"Random tensor now: \n {tensor}")

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"dim1-catted tensor: \n {t1}")

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(f"dim0-catted tensor: \n {t1}")

Random tensor: 
 tensor([[0.7181, 0.2421, 0.6371],
        [0.1323, 0.4799, 0.3784]])
Random tensor now: 
 tensor([[0.7181, 0.2421, 1.0000],
        [0.1323, 0.4799, 1.0000]])
dim1-catted tensor: 
 tensor([[0.7181, 0.2421, 1.0000, 0.7181, 0.2421, 1.0000, 0.7181, 0.2421, 1.0000],
        [0.1323, 0.4799, 1.0000, 0.1323, 0.4799, 1.0000, 0.1323, 0.4799, 1.0000]])
dim0-catted tensor: 
 tensor([[0.7181, 0.2421, 1.0000],
        [0.1323, 0.4799, 1.0000],
        [0.7181, 0.2421, 1.0000],
        [0.1323, 0.4799, 1.0000],
        [0.7181, 0.2421, 1.0000],
        [0.1323, 0.4799, 1.0000]])


In [9]:
print(f"Multiplication is element-wise, a priori,\n{tensor * tensor}")
print(f"Mail your Matrix multiplication today!:n{tensor @ tensor.T}")

Multiplication is element-wise, a priori,
tensor([[0.5156, 0.0586, 1.0000],
        [0.0175, 0.2303, 1.0000]])
Mail your Matrix multiplication today!:ntensor([[1.5743, 1.2112],
        [1.2112, 1.2479]])


In [10]:
print(f"There is some unsexy tension between in-place operations and derivatives; thus, torch hates this trick. \n {tensor.add_(5)}")

There is some unsexy tension between in-place operations and derivatives; thus, torch hates this trick. 
 tensor([[5.7181, 5.2421, 6.0000],
        [5.1323, 5.4799, 6.0000]])


In [11]:
n = np.ones(4)
t1 = torch.tensor(n)
t2 = torch.from_numpy(n)
n[0] = 0
np.add(n, 1, out=n)
print(f"Numpy and Tensor love (explicit) sharing!\n {t1} \n {t2}")

t2[0] = 10
print(f"Both ways: \n {t2} \n {n}")

Numpy and Tensor love (explicit) sharing!
 tensor([1., 1., 1., 1.], dtype=torch.float64) 
 tensor([1., 2., 2., 2.], dtype=torch.float64)
Both ways: 
 tensor([10.,  2.,  2.,  2.], dtype=torch.float64) 
 [10.  2.  2.  2.]


In [12]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)